#!/bin/sh

FILE=$1

# Check if argument was provided
if [ -z $FILE ]
then
    echo "You must provide file name."
    exit 1
fi

echo "Checking if file $FILE is installed."
INSTALLED=0

# Check if file exists
if [ ! -e ~/.$FILE ]
then
    echo "File $FILE does not exist. Assuming not installed."
else
    # Check if file is symlink. If so, we assume it is installed.
    if [ -h ~/.$FILE ]
    then
        echo "Installed."
        INSTALLED=1
    else
        echo "Not installed."
    fi
fi

# Exit if file installed.
if [ $INSTALLED -eq 1 ]
then
    echo "Nothing to do, exiting."
    exit 1
fi

# Backup file
BACKUPDIR=~/dotfiles/backup/
echo Backing up to $BACKUPDIR

if [ ! -d $BACKUPDIR ]
then
    echo "Backup dir does not exist. Creating one."
    mkdir $BACKUPDIR
    RES=$?
    if [ ! $RES -eq 0 ]
    then
        echo "Failed to create backup dir $BACKUPDIR. Exiting."
        exit 1
    else
        echo "Backup directory created."
    fi
fi

# Full path of the target file
SRCPATH="$HOME/."$FILE
# Full path of the new file
NEWFILE="$HOME/dotfiles/$FILE.symlink"

# Backup existing...
mv -v $SRCPATH $BACKUPDIR

# And link to the new one
ln -sv $NEWFILE $SRCPATH


echo "Done."
exit 0
